// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tourist_Project_MVC.Data;

#nullable disable

namespace Tourist_Project_MVC.Migrations
{
    [DbContext(typeof(TouristContext))]
    partial class TouristContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-id",
                            ConcurrencyStamp = "STATIC-ROLE-STAMP-1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-user-id",
                            ConcurrencyStamp = "STATIC-ROLE-STAMP-2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "role-admin-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-12345",
                            Email = "admin@egyxplore.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EGYXPLORE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEOM7OCjj2Qn35RIy2ZkWbwA5OiG6BP0kf501wx6tAaZeWYV8w4SiIUX35viVhiAmgw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC-STAMP-12345",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Lat")
                        .HasColumnType("real");

                    b.Property<float>("Long")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OpeningHours")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TicketPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Visits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Archaeological",
                            City = "Giza",
                            Description = "One of the Seven Wonders of the Ancient World.",
                            Lat = 29.9792f,
                            Long = 31.1342f,
                            Name = "The Great Pyramids of Giza",
                            Status = "Active",
                            TicketPrice = 200.00m,
                            Visits = 18200
                        },
                        new
                        {
                            Id = 2,
                            Category = "Archaeological",
                            City = "Giza",
                            Description = "The iconic limestone statue on the Giza Plateau.",
                            Lat = 29.9753f,
                            Long = 31.1376f,
                            Name = "The Great Sphinx",
                            Status = "Active",
                            TicketPrice = 0.00m,
                            Visits = 15600
                        },
                        new
                        {
                            Id = 3,
                            Category = "Temple",
                            City = "Luxor",
                            Description = "The largest ancient religious site in the world.",
                            Lat = 25.7188f,
                            Long = 32.6573f,
                            Name = "Karnak Temple Complex",
                            Status = "Active",
                            TicketPrice = 150.00m,
                            Visits = 12450
                        },
                        new
                        {
                            Id = 4,
                            Category = "Archaeological",
                            City = "Luxor",
                            Description = "Royal burial ground of pharaohs from the New Kingdom era.",
                            Lat = 25.7402f,
                            Long = 32.6014f,
                            Name = "Valley of the Kings",
                            Status = "Active",
                            TicketPrice = 180.00m,
                            Visits = 10300
                        },
                        new
                        {
                            Id = 5,
                            Category = "Temple",
                            City = "Aswan",
                            Description = "Rock-cut temples of Ramesses II on the shores of Lake Nasser.",
                            Lat = 22.3372f,
                            Long = 31.6258f,
                            Name = "Abu Simbel Temples",
                            Status = "Active",
                            TicketPrice = 220.00m,
                            Visits = 8900
                        },
                        new
                        {
                            Id = 6,
                            Category = "Historical",
                            City = "Alexandria",
                            Description = "A 15th-century defensive fortress in Alexandria.",
                            Lat = 31.2141f,
                            Long = 29.8858f,
                            Name = "Qaitbay Citadel",
                            Status = "Active",
                            TicketPrice = 40.00m,
                            Visits = 7200
                        },
                        new
                        {
                            Id = 7,
                            Category = "Museum",
                            City = "Cairo",
                            Description = "Home to the world's largest collection of ancient Egyptian artifacts.",
                            Lat = 30.0478f,
                            Long = 31.2336f,
                            Name = "Egyptian Museum",
                            Status = "Active",
                            TicketPrice = 100.00m,
                            Visits = 22100
                        },
                        new
                        {
                            Id = 8,
                            Category = "Religious",
                            City = "South Sinai",
                            Description = "One of the oldest Christian monasteries in the world.",
                            Lat = 28.5569f,
                            Long = 33.9758f,
                            Name = "Saint Catherine's Monastery",
                            Status = "Active",
                            TicketPrice = 50.00m,
                            Visits = 4500
                        },
                        new
                        {
                            Id = 9,
                            Category = "Natural",
                            City = "Matrouh",
                            Description = "A remote oasis home to the Oracle Temple of Amun.",
                            Lat = 29.2031f,
                            Long = 25.5195f,
                            Name = "Siwa Oasis",
                            Status = "Active",
                            TicketPrice = 30.00m,
                            Visits = 3200
                        },
                        new
                        {
                            Id = 10,
                            Category = "Natural",
                            City = "Fayoum",
                            Description = "UNESCO World Heritage Site with fossils of ancient whales.",
                            Lat = 29.2711f,
                            Long = 30.0389f,
                            Name = "Wadi El Hitan (Whale Valley)",
                            Status = "Pending",
                            TicketPrice = 25.00m,
                            Visits = 1800
                        },
                        new
                        {
                            Id = 11,
                            Category = "Temple",
                            City = "Qena",
                            Description = "One of Egypt's best-preserved temples dedicated to Hathor.",
                            Lat = 26.1415f,
                            Long = 32.6697f,
                            Name = "Dendera Temple",
                            Status = "Active",
                            TicketPrice = 80.00m,
                            Visits = 5600
                        },
                        new
                        {
                            Id = 12,
                            Category = "Archaeological",
                            City = "Sharqia",
                            Description = "The forgotten pharaonic capital hiding undiscovered royal treasures.",
                            Lat = 30.9769f,
                            Long = 31.8731f,
                            Name = "Tanis (Ancient City)",
                            Status = "Pending",
                            TicketPrice = 20.00m,
                            Visits = 900
                        },
                        new
                        {
                            Id = 13,
                            Category = "Archaeological",
                            City = "Giza",
                            Description = "Home to the Bent Pyramid and Red Pyramid built by Pharaoh Sneferu.",
                            Lat = 29.8086f,
                            Long = 31.2214f,
                            Name = "Dahshur Pyramids",
                            Status = "Active",
                            TicketPrice = 60.00m,
                            Visits = 4100
                        },
                        new
                        {
                            Id = 14,
                            Category = "Museum",
                            City = "Giza",
                            Description = "The world's largest archaeological museum with over 100,000 artifacts.",
                            Lat = 29.9884f,
                            Long = 31.1188f,
                            Name = "The Grand Egyptian Museum",
                            Status = "Active",
                            TicketPrice = 250.00m,
                            Visits = 9800
                        },
                        new
                        {
                            Id = 15,
                            Category = "Historical",
                            City = "Cairo",
                            Description = "A medieval Islamic fortification built by Saladin in the 12th century.",
                            Lat = 30.0287f,
                            Long = 31.2599f,
                            Name = "Saladin Citadel",
                            Status = "Inactive",
                            TicketPrice = 60.00m,
                            Visits = 6700
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("MissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsReward")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Capture a panoramic photo of all three pyramids at sunset",
                            DestinationId = 1,
                            MissionType = "Photography",
                            PointsReward = 150,
                            Title = "Pyramid Panorama"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Visit at least 5 different tombs inside the Valley of the Kings",
                            DestinationId = 4,
                            MissionType = "Exploration",
                            PointsReward = 200,
                            Title = "Valley Explorer"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Attend the Sound and Light Show at Karnak Temple",
                            DestinationId = 3,
                            MissionType = "Cultural",
                            PointsReward = 100,
                            Title = "Karnak Night Show"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Witness the solar alignment phenomenon at Abu Simbel Temple",
                            DestinationId = 5,
                            MissionType = "Adventure",
                            PointsReward = 300,
                            Title = "Sun Alignment Witness"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Explore the Oracle Temple of Amun in Siwa Oasis",
                            DestinationId = 9,
                            MissionType = "Discovery",
                            PointsReward = 250,
                            Title = "Hidden Oasis Quest"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Photograph 10 different whale fossils in Wadi El Hitan",
                            DestinationId = 10,
                            MissionType = "Photography",
                            PointsReward = 180,
                            Title = "Whale Valley Fossils"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Locate and photograph 5 artifacts from Tutankhamun's collection in the Egyptian Museum",
                            DestinationId = 7,
                            MissionType = "Cultural",
                            PointsReward = 120,
                            Title = "Tutankhamun Treasure Hunt"
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Redemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsRedeemed")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedemptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RewardId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TouristId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.HasIndex("TouristId");

                    b.ToTable("Redemptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MARRIOTT15-EGY",
                            PointsRedeemed = 200,
                            RedemptionDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RewardId = 1,
                            Status = "Active",
                            TouristId = 2
                        },
                        new
                        {
                            Id = 2,
                            Code = "NILE-CRUISE-EMC",
                            PointsRedeemed = 300,
                            RedemptionDate = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RewardId = 3,
                            Status = "Used",
                            TouristId = 1
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointsRequired")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Get 15% discount on your next stay at Cairo Marriott Hotel",
                            ExpirationDate = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PointsRequired = 200,
                            QuantityAvailable = 50,
                            RewardType = "Discount",
                            SponsorId = 1,
                            Title = "15% Off Marriott Cairo"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Complimentary business class upgrade on domestic EgyptAir flights",
                            ExpirationDate = new DateTime(2027, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PointsRequired = 500,
                            QuantityAvailable = 10,
                            RewardType = "Ticket",
                            SponsorId = 2,
                            Title = "Free EgyptAir Upgrade"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Complimentary one-day Nile cruise provided by Emeco Travel",
                            ExpirationDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PointsRequired = 300,
                            QuantityAvailable = 20,
                            RewardType = "Tour",
                            SponsorId = 3,
                            Title = "Free Nile Cruise Day"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Enjoy 20% off at the historic Sofitel Luxor Winter Palace Hotel",
                            ExpirationDate = new DateTime(2027, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PointsRequired = 250,
                            QuantityAvailable = 30,
                            RewardType = "Discount",
                            SponsorId = 4,
                            Title = "20% Off Luxor Winter Palace"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Exclusive Nile-view sunset dinner for two at Hilton Aswan",
                            ExpirationDate = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PointsRequired = 400,
                            QuantityAvailable = 15,
                            RewardType = "Experience",
                            SponsorId = 5,
                            Title = "Hilton Aswan Sunset Dinner"
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "16 Saray El Gezira St, Zamalek, Cairo",
                            ContactNumber = 223456789,
                            Name = "Cairo Marriott Hotel",
                            Type = "Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cairo International Airport, Cairo",
                            ContactNumber = 290777000,
                            Name = "EgyptAir",
                            Type = "Airline"
                        },
                        new
                        {
                            Id = 3,
                            Address = "26 Tahrir Square, Downtown Cairo",
                            ContactNumber = 222756000,
                            Name = "Emeco Travel",
                            Type = "Tourism Agency"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Corniche El Nile, Luxor",
                            ContactNumber = 953580422,
                            Name = "Sofitel Luxor Winter Palace",
                            Type = "Hotel"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Elephantine Island, Aswan",
                            ContactNumber = 972780222,
                            Name = "Hilton Aswan",
                            Type = "Hotel"
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Tourist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("point_Balance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tourists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.hassan@email.com",
                            IdNumber = "EG123456789",
                            Name = "Ahmed Hassan",
                            Nationality = "Egyptian",
                            Password = "HashedPass123",
                            RegisterDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            point_Balance = 350
                        },
                        new
                        {
                            Id = 2,
                            Email = "james.wilson@email.com",
                            Name = "James Wilson",
                            Nationality = "American",
                            Passport = "US987654321",
                            Password = "HashedPass456",
                            RegisterDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            point_Balance = 120
                        },
                        new
                        {
                            Id = 3,
                            Email = "sophie.muller@email.com",
                            Name = "Sophie Müller",
                            Nationality = "German",
                            Passport = "DE456789123",
                            Password = "HashedPass789",
                            RegisterDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            point_Balance = 200
                        },
                        new
                        {
                            Id = 4,
                            Email = "yuki.tanaka@email.com",
                            Name = "Yuki Tanaka",
                            Nationality = "Japanese",
                            Passport = "JP321654987",
                            Password = "HashedPassABC",
                            RegisterDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            point_Balance = 80
                        },
                        new
                        {
                            Id = 5,
                            Email = "mohamed.ali@email.com",
                            IdNumber = "EG987654321",
                            Name = "Mohamed Ali",
                            Nationality = "Egyptian",
                            Password = "HashedPassXYZ",
                            RegisterDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            point_Balance = 500
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.TripDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("TripPlanId")
                        .HasColumnType("int");

                    b.Property<int>("Visit_Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TripPlanId");

                    b.ToTable("TripDestinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 1,
                            TripPlanId = 1,
                            Visit_Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 7,
                            TripPlanId = 1,
                            Visit_Order = 2
                        },
                        new
                        {
                            Id = 3,
                            ArrivalDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 3,
                            TripPlanId = 1,
                            Visit_Order = 3
                        },
                        new
                        {
                            Id = 4,
                            ArrivalDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 5,
                            TripPlanId = 1,
                            Visit_Order = 4
                        },
                        new
                        {
                            Id = 5,
                            ArrivalDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 9,
                            TripPlanId = 2,
                            Visit_Order = 1
                        },
                        new
                        {
                            Id = 6,
                            ArrivalDate = new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 10,
                            TripPlanId = 2,
                            Visit_Order = 2
                        },
                        new
                        {
                            Id = 7,
                            ArrivalDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 11,
                            TripPlanId = 2,
                            Visit_Order = 3
                        },
                        new
                        {
                            Id = 8,
                            ArrivalDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 14,
                            TripPlanId = 3,
                            Visit_Order = 1
                        },
                        new
                        {
                            Id = 9,
                            ArrivalDate = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 4,
                            TripPlanId = 3,
                            Visit_Order = 2
                        },
                        new
                        {
                            Id = 10,
                            ArrivalDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 3,
                            TripPlanId = 3,
                            Visit_Order = 3
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.TripPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TouristId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TouristId");

                    b.ToTable("TripPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Title = "Classic Egypt Tour",
                            TouristId = 2
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Title = "Hidden Wonders of Egypt",
                            TouristId = 3
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Title = "Nile Valley Explorer",
                            TouristId = 1
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.UserMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Completed_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TouristId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("TouristId");

                    b.ToTable("UserMissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed_At = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MissionId = 1,
                            PointsEarned = 150,
                            Status = "Completed",
                            TouristId = 2
                        },
                        new
                        {
                            Id = 2,
                            Completed_At = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MissionId = 2,
                            PointsEarned = 0,
                            Status = "In Progress",
                            TouristId = 3
                        },
                        new
                        {
                            Id = 3,
                            Completed_At = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MissionId = 2,
                            PointsEarned = 200,
                            Status = "Completed",
                            TouristId = 1
                        },
                        new
                        {
                            Id = 4,
                            Completed_At = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MissionId = 1,
                            PointsEarned = 0,
                            Status = "In Progress",
                            TouristId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourist_Project_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Mission", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Destination", "Destination")
                        .WithMany("Missions")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Redemption", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Reward", "Reward")
                        .WithMany("Redemptions")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourist_Project_MVC.Models.Tourist", "Tourist")
                        .WithMany("Redemptions")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Reward", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Sponsor", "Sponsor")
                        .WithMany("Rewards")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.TripDestination", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Destination", "Destination")
                        .WithMany("TripDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourist_Project_MVC.Models.TripPlan", "TripPlan")
                        .WithMany("TripDestinations")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.TripPlan", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Tourist", "Tourist")
                        .WithMany("TripPlans")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.UserMission", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Mission", "Mission")
                        .WithMany("UserMissions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourist_Project_MVC.Models.Tourist", "Tourist")
                        .WithMany("UserMissions")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Destination", b =>
                {
                    b.Navigation("Missions");

                    b.Navigation("TripDestinations");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Mission", b =>
                {
                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Reward", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Sponsor", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Tourist", b =>
                {
                    b.Navigation("Redemptions");

                    b.Navigation("TripPlans");

                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.TripPlan", b =>
                {
                    b.Navigation("TripDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
